-
  name: 'Reset password'
  uriPattern: 'neos/passwordreset'
  defaults:
    '@controller': 'Reset'
    '@package': 'NeosRulez.Neos.PasswordReset'
    '@action': 'execute'
  appendExceedingArguments: true
