Neos:
  Flow:
    mvc:
      routes:
        'NeosRulez.Neos.PasswordReset': true
  Neos:
    fusion:
      autoInclude:
        NeosRulez.Neos.PasswordReset: true
    userInterface:
      translation:
        autoInclude:
          NeosRulez.Neos.PasswordReset:
            - Main
NeosRulez:
  Neos:
    PasswordReset:
      senderMail: 'noreply@foo.com'
      adminMail: 'admin@foo.com' # Disable (set it to false) if you not want to recieve info mails.
      passwordLength: 8
      tokenLifetime: 5 # Reset token lifetime in minutes
      confirmation:
        templatePathAndFilename: 'resource://NeosRulez.Neos.PasswordReset/Private/Templates/Confirmation.html'
      reset:
        templatePathAndFilename: 'resource://NeosRulez.Neos.PasswordReset/Private/Templates/Reset.html'
